### PR TITLE
Switch to fetcher, improve Error handling

### PR DESCRIPTION
**Pull request by dylanegan**
As per https://pipelinedeals.leankit.com/Boards/View/511725601/511811371, @staskie has a requirement for improved PipelineDeals.js error handling, where improved means working in this case.

I've copied the code from [fetcher.js](https://github.com/PipelineDeals/pipeline_deals/blob/master/webpack/modules/fetcher.js) for now because I recently improved it there. I'll probably want to extract that to share between projects in the future or have it imported from here.

@staskie with regards to the second part of the card, accessing information using Promises, I'll show you tomorrow, but I'll document an example below using redux-saga and redux-form.

```ruby
class ObjectController
  def create
    @object = Object.create(params[:object])
    if @object = Object.create(params[:id])
      render json: @profile
    else
      render json: { "message": "Profile (#{params[:id]}) not found." }, status: 404
    end
  end
end
```

```js
export function * createObjectSaga ({ payload }) {
  try {
    const object = yield call([pd, pd.object])
    const response = yield call([object, object.create], payload)

    yield put(actions.createObjectSuccess({ object: response.object }))
  } catch (error) {
    error.response.json().then(json => {
      yield put(actions.createObjectFailure({ _error: json.message }))
    })
  }
}
```

From the `redux-form` part of things you'll want to make sure the actions you're calling are defined as part of the form itself using the `onSubmit` option.

```js
onSubmit: onSubmitActions(constants.CREATE_OBJECT_REQUEST, constants.CREATE_OBJECT_SUCCESS, constants.CREATE_OBJECT_FAILURE)
```

### CODE REVIEW

**Comment by dylanegan** [comment]
```js
export function * createObjectSaga ({ payload }) {
  try {
    ...
  } catch (error) {
    const json = yield call([error, error.response.json])
    yield put(actions.createObjectFailure({ _error: json.message }))
  }
}
```

**Comment by staskie** [comment]
@dylanegan I finally found some time to get back to this. I tried both approaches and none of them worked for me.

This is what I am getting:

```
    error.response.json().then(json => {
      yield put(actions.createObjectFailure({ _error: json.message }))
    })
```

```
    (Emitted value instead of an instance of Error) 
    /Users/dominik/working/pipeline/pipeline_deals/webpack/admin/custom_fields/sagas/Label.js
      30:7  error  Parsing error: yield is a reserved word

      28 |     exception.response.json().then((data) => {
      29 |       console.log('promise resolved', data)
    > 30 |       yield put(actions.newCustomFieldLabelFormFailure({ _error: exception }))
         |       ^
      31 |     })
```
Which means that I can not use yield from the resolved promise.

When I try the second approach:

```
const json = yield call([error, error.response.json])
    yield put(actions.createObjectFailure({ _error: json.message }))
```

I get this:

```
    utils.js?1f12:197 uncaught at rootSaga 
     at rootSaga 
     at takeEvery 
     at newCustomFieldLabelSaga 
     TypeError: Failed to execute 'json' on 'Response': Illegal invocation
```

Any ideas what to try next?

**Comment by dylanegan** [comment]
@staskie as per HipChat, let me know when you've tried your last bit and I can hop on and try. As per the call last week this was just pseudo code and not tested so I'd need to spend time to get it actually working.

**Comment by staskie** [comment]
Okay, the last thing I tried to fix was the syntax from the first error about yield being a reserved word. Yield can not be called from the function, it has to be called from the generator. So I replaced the code with:

```
    yield * exception.response.json().then(function * (data) {
      console.log('promise resolved', data)
      yield put(actions.newCustomFieldLabelFormFailure({ _error: exception }))
    })
```

Still no luck. Now I need your help :)

**Comment by dylanegan** [comment]
@staskie will ping you on HipChat.

**Comment by dylanegan** [comment]
As per HipChat, the pseudocode was just missing a `.response`.

**Pull request merged**
